FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

ENV ASPNETCORE_URLS="https://+:8081;http://+:8080"
ENV ASPNETCORE_HTTPS_PORT=8003
ENV ASPNETCORE_ENVIRONMENT="Development"

EXPOSE 8080
EXPOSE 8081

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BudgetManager.Api/BudgetManager.Api.csproj", "BudgetManager.Api/"]
RUN dotnet restore "BudgetManager.Api/BudgetManager.Api.csproj"
COPY . .
WORKDIR "/src/BudgetManager.Api"
RUN dotnet build "BudgetManager.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BudgetManager.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BudgetManager.Api.dll"]