/* tslint:disable */
/* eslint-disable */
/**
 * ManagerWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BankAccountModel,
    BankAccountModelFromJSON,
    BankAccountModelToJSON,
    BankBalanceModel,
    BankBalanceModelFromJSON,
    BankBalanceModelToJSON,
} from '../models';

export interface BankAccountGetAllAccountBalanceGetRequest {
    toDate?: Date | null;
}

/**
 * BankAccountApi - interface
 * 
 * @export
 * @interface BankAccountApiInterface
 */
export interface BankAccountApiInterface {
    /**
     * 
     * @param {Date} [toDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankAccountApiInterface
     */
    bankAccountGetAllAccountBalanceGetRaw(requestParameters: BankAccountGetAllAccountBalanceGetRequest): Promise<runtime.ApiResponse<Array<BankBalanceModel>>>;

    /**
     */
    bankAccountGetAllAccountBalanceGet(requestParameters: BankAccountGetAllAccountBalanceGetRequest): Promise<Array<BankBalanceModel>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankAccountApiInterface
     */
    bankAccountGetAllGetRaw(): Promise<runtime.ApiResponse<Array<BankAccountModel>>>;

    /**
     */
    bankAccountGetAllGet(): Promise<Array<BankAccountModel>>;

}

/**
 * 
 */
export class BankAccountApi extends runtime.BaseAPI implements BankAccountApiInterface {

    /**
     */
    async bankAccountGetAllAccountBalanceGetRaw(requestParameters: BankAccountGetAllAccountBalanceGetRequest): Promise<runtime.ApiResponse<Array<BankBalanceModel>>> {
        const queryParameters: any = {};

        if (requestParameters.toDate !== undefined) {
            queryParameters['toDate'] = (requestParameters.toDate as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bankAccount/getAllAccountBalance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BankBalanceModelFromJSON));
    }

    /**
     */
    async bankAccountGetAllAccountBalanceGet(requestParameters: BankAccountGetAllAccountBalanceGetRequest): Promise<Array<BankBalanceModel>> {
        const response = await this.bankAccountGetAllAccountBalanceGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async bankAccountGetAllGetRaw(): Promise<runtime.ApiResponse<Array<BankAccountModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bankAccount/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BankAccountModelFromJSON));
    }

    /**
     */
    async bankAccountGetAllGet(): Promise<Array<BankAccountModel>> {
        const response = await this.bankAccountGetAllGetRaw();
        return await response.value();
    }

}
