/* tslint:disable */
/* eslint-disable */
/**
 * ManagerWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * HomeApi - interface
 * 
 * @export
 * @interface HomeApiInterface
 */
export interface HomeApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    cryptoOverviewGetRaw(): Promise<runtime.ApiResponse<void>>;

    /**
     */
    cryptoOverviewGet(): Promise<void>;

}

/**
 * 
 */
export class HomeApi extends runtime.BaseAPI implements HomeApiInterface {

    /**
     */
    async cryptoOverviewGetRaw(): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/crypto-overview`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cryptoOverviewGet(): Promise<void> {
        await this.cryptoOverviewGetRaw();
    }

}
