version: '3.8'

services:
  authapi:
    build:
      context: .
      dockerfile: /BudgetManager.AuthApi/dockerfile
    container_name: authapi
    ports:
      - "8000:8080"  # HTTP
      - "8001:8081"  # HTTPS
    networks:
      - budget-manager-net
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetmanager.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_ENVIRONMENT=Development

  mainapi:
    build:
      context: .
      dockerfile: /BudgetManager.Api/dockerfile
    container_name: mainapi
    ports:
      - "8002:8080"  # HTTP
      - "8003:8081"  # HTTPS
    depends_on:
      - authapi
    networks:
      - budget-manager-net
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetmanager.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthApi__ValidateUrl=https://authapi:8081/auth/v1/validate
      - AuthApi__DataUrl=https://authapi:8081/auth/v1/tokendata
      - Rabbit__RabbitMqUri=rabbitmq://rabbitmq:5672/
      - DbSetting__ConnectionString=Server=host.docker.internal;Database=BudgetManager;User ID=${SQL_USER};Password=${SQL_PASSWORD};TrustServerCertificate=True
    extra_hosts:
      - "host.docker.internal:host-gateway"

  finapi:
    build:
      context: .
      dockerfile: /BudgetManager.FinancialApi/dockerfile
    container_name: finapi
    ports:
      - "8004:8080"  # HTTP
      - "8005:8081"  # HTTPS
    depends_on:
      - authapi
    networks:
      - budget-manager-net
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetmanager.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthApi__BaseUrl=https://authapi:8081

networks:
  budget-manager-net:
    external: true