/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    BrokerReportToProcessState,
    BrokerReportToProcessStateFromJSON,
    BrokerReportToProcessStateFromJSONTyped,
    BrokerReportToProcessStateToJSON,
} from './BrokerReportToProcessState';
import {
    BrokerReportType,
    BrokerReportTypeFromJSON,
    BrokerReportTypeFromJSONTyped,
    BrokerReportTypeToJSON,
} from './BrokerReportType';
import {
    EnumItem,
    EnumItemFromJSON,
    EnumItemFromJSONTyped,
    EnumItemToJSON,
} from './EnumItem';
import {
    UserIdentity,
    UserIdentityFromJSON,
    UserIdentityFromJSONTyped,
    UserIdentityToJSON,
} from './UserIdentity';

/**
 * 
 * @export
 * @class BrokerReportToProcess
 */
export class BrokerReportToProcess {
    /**
     * 
     * @type {number}
     * @memberof BrokerReportToProcess
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof BrokerReportToProcess
     */
    importedTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof BrokerReportToProcess
     */
    fileContentBase64?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BrokerReportToProcess
     */
    brokerReportToProcessStateId?: number;
    /**
     * 
     * @type {BrokerReportToProcessState}
     * @memberof BrokerReportToProcess
     */
    brokerReportToProcessState?: BrokerReportToProcessState;
    /**
     * 
     * @type {number}
     * @memberof BrokerReportToProcess
     */
    userIdentityId?: number;
    /**
     * 
     * @type {UserIdentity}
     * @memberof BrokerReportToProcess
     */
    userIdentity?: UserIdentity;
    /**
     * 
     * @type {number}
     * @memberof BrokerReportToProcess
     */
    brokerReportTypeId?: number;
    /**
     * 
     * @type {BrokerReportType}
     * @memberof BrokerReportToProcess
     */
    brokerReportType?: BrokerReportType;
    /**
     * 
     * @type {number}
     * @memberof BrokerReportToProcess
     */
    brokerId?: number;
    /**
     * 
     * @type {EnumItem}
     * @memberof BrokerReportToProcess
     */
    broker?: EnumItem;
}

export function BrokerReportToProcessFromJSON(json: any): BrokerReportToProcess {
    return BrokerReportToProcessFromJSONTyped(json, false);
}

export function BrokerReportToProcessFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrokerReportToProcess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'importedTime': !exists(json, 'importedTime') ? undefined : (new Date(json['importedTime'])),
        'fileContentBase64': !exists(json, 'fileContentBase64') ? undefined : json['fileContentBase64'],
        'brokerReportToProcessStateId': !exists(json, 'brokerReportToProcessStateId') ? undefined : json['brokerReportToProcessStateId'],
        'brokerReportToProcessState': !exists(json, 'brokerReportToProcessState') ? undefined : BrokerReportToProcessStateFromJSON(json['brokerReportToProcessState']),
        'userIdentityId': !exists(json, 'userIdentityId') ? undefined : json['userIdentityId'],
        'userIdentity': !exists(json, 'userIdentity') ? undefined : UserIdentityFromJSON(json['userIdentity']),
        'brokerReportTypeId': !exists(json, 'brokerReportTypeId') ? undefined : json['brokerReportTypeId'],
        'brokerReportType': !exists(json, 'brokerReportType') ? undefined : BrokerReportTypeFromJSON(json['brokerReportType']),
        'brokerId': !exists(json, 'brokerId') ? undefined : json['brokerId'],
        'broker': !exists(json, 'broker') ? undefined : EnumItemFromJSON(json['broker']),
    };
}

export function BrokerReportToProcessToJSON(value?: BrokerReportToProcess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'importedTime': value.importedTime === undefined ? undefined : (value.importedTime.toISOString()),
        'fileContentBase64': value.fileContentBase64,
        'brokerReportToProcessStateId': value.brokerReportToProcessStateId,
        'brokerReportToProcessState': BrokerReportToProcessStateToJSON(value.brokerReportToProcessState),
        'userIdentityId': value.userIdentityId,
        'userIdentity': UserIdentityToJSON(value.userIdentity),
        'brokerReportTypeId': value.brokerReportTypeId,
        'brokerReportType': BrokerReportTypeToJSON(value.brokerReportType),
        'brokerId': value.brokerId,
        'broker': EnumItemToJSON(value.broker),
    };
}
