/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    ComodityType,
    ComodityTypeFromJSON,
    ComodityTypeFromJSONTyped,
    ComodityTypeToJSON,
} from './ComodityType';
import {
    CurrencySymbol,
    CurrencySymbolFromJSON,
    CurrencySymbolFromJSONTyped,
    CurrencySymbolToJSON,
} from './CurrencySymbol';
import {
    UserIdentity,
    UserIdentityFromJSON,
    UserIdentityFromJSONTyped,
    UserIdentityToJSON,
} from './UserIdentity';

/**
 * 
 * @export
 * @class ComodityTradeHistory
 */
export class ComodityTradeHistory {
    /**
     * 
     * @type {number}
     * @memberof ComodityTradeHistory
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof ComodityTradeHistory
     */
    tradeTimeStamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ComodityTradeHistory
     */
    comodityTypeId?: number;
    /**
     * 
     * @type {ComodityType}
     * @memberof ComodityTradeHistory
     */
    comodityType?: ComodityType;
    /**
     * 
     * @type {number}
     * @memberof ComodityTradeHistory
     */
    tradeSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ComodityTradeHistory
     */
    tradeValue?: number;
    /**
     * 
     * @type {number}
     * @memberof ComodityTradeHistory
     */
    currencySymbolId?: number;
    /**
     * 
     * @type {CurrencySymbol}
     * @memberof ComodityTradeHistory
     */
    currencySymbol?: CurrencySymbol;
    /**
     * 
     * @type {number}
     * @memberof ComodityTradeHistory
     */
    userIdentityId?: number;
    /**
     * 
     * @type {UserIdentity}
     * @memberof ComodityTradeHistory
     */
    userIdentity?: UserIdentity;
    /**
     * 
     * @type {string}
     * @memberof ComodityTradeHistory
     */
    company?: string | null;
}

export function ComodityTradeHistoryFromJSON(json: any): ComodityTradeHistory {
    return ComodityTradeHistoryFromJSONTyped(json, false);
}

export function ComodityTradeHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComodityTradeHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tradeTimeStamp': !exists(json, 'tradeTimeStamp') ? undefined : (new Date(json['tradeTimeStamp'])),
        'comodityTypeId': !exists(json, 'comodityTypeId') ? undefined : json['comodityTypeId'],
        'comodityType': !exists(json, 'comodityType') ? undefined : ComodityTypeFromJSON(json['comodityType']),
        'tradeSize': !exists(json, 'tradeSize') ? undefined : json['tradeSize'],
        'tradeValue': !exists(json, 'tradeValue') ? undefined : json['tradeValue'],
        'currencySymbolId': !exists(json, 'currencySymbolId') ? undefined : json['currencySymbolId'],
        'currencySymbol': !exists(json, 'currencySymbol') ? undefined : CurrencySymbolFromJSON(json['currencySymbol']),
        'userIdentityId': !exists(json, 'userIdentityId') ? undefined : json['userIdentityId'],
        'userIdentity': !exists(json, 'userIdentity') ? undefined : UserIdentityFromJSON(json['userIdentity']),
        'company': !exists(json, 'company') ? undefined : json['company'],
    };
}

export function ComodityTradeHistoryToJSON(value?: ComodityTradeHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tradeTimeStamp': value.tradeTimeStamp === undefined ? undefined : (value.tradeTimeStamp.toISOString()),
        'comodityTypeId': value.comodityTypeId,
        'comodityType': ComodityTypeToJSON(value.comodityType),
        'tradeSize': value.tradeSize,
        'tradeValue': value.tradeValue,
        'currencySymbolId': value.currencySymbolId,
        'currencySymbol': CurrencySymbolToJSON(value.currencySymbol),
        'userIdentityId': value.userIdentityId,
        'userIdentity': UserIdentityToJSON(value.userIdentity),
        'company': value.company,
    };
}
