/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.FinancialApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class CryptoDataV2
 */
export class CryptoDataV2 {
    /**
     * 
     * @type {number}
     * @memberof CryptoDataV2
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof CryptoDataV2
     */
    ticker?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CryptoDataV2
     */
    time?: Date;
}

export function CryptoDataV2FromJSON(json: any): CryptoDataV2 {
    return CryptoDataV2FromJSONTyped(json, false);
}

export function CryptoDataV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoDataV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'price': !exists(json, 'price') ? undefined : json['price'],
        'ticker': !exists(json, 'ticker') ? undefined : json['ticker'],
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
    };
}

export function CryptoDataV2ToJSON(value?: CryptoDataV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price': value.price,
        'ticker': value.ticker,
        'time': value.time === undefined ? undefined : (value.time.toISOString()),
    };
}
