/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ECurrencySymbol {
    Usd = 'USD',
    Czk = 'CZK',
    Gbp = 'GBP',
    Eur = 'EUR',
    Jpy = 'JPY'
}

export function ECurrencySymbolFromJSON(json: any): ECurrencySymbol {
    return ECurrencySymbolFromJSONTyped(json, false);
}

export function ECurrencySymbolFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECurrencySymbol {
    return json as ECurrencySymbol;
}

export function ECurrencySymbolToJSON(value?: ECurrencySymbol | null): any {
    return value as any;
}

