/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class OtherInvestmentModel
 */
export class OtherInvestmentModel {
    /**
     * 
     * @type {number}
     * @memberof OtherInvestmentModel
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof OtherInvestmentModel
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof OtherInvestmentModel
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OtherInvestmentModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OtherInvestmentModel
     */
    openingBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof OtherInvestmentModel
     */
    userIdentityId?: number;
    /**
     * 
     * @type {number}
     * @memberof OtherInvestmentModel
     */
    currencySymbolId?: number;
}

export function OtherInvestmentModelFromJSON(json: any): OtherInvestmentModel {
    return OtherInvestmentModelFromJSONTyped(json, false);
}

export function OtherInvestmentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtherInvestmentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'openingBalance': !exists(json, 'openingBalance') ? undefined : json['openingBalance'],
        'userIdentityId': !exists(json, 'userIdentityId') ? undefined : json['userIdentityId'],
        'currencySymbolId': !exists(json, 'currencySymbolId') ? undefined : json['currencySymbolId'],
    };
}

export function OtherInvestmentModelToJSON(value?: OtherInvestmentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'code': value.code,
        'name': value.name,
        'openingBalance': value.openingBalance,
        'userIdentityId': value.userIdentityId,
        'currencySymbolId': value.currencySymbolId,
    };
}
