/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class StockTradeHistoryModel
 */
export class StockTradeHistoryModel {
    /**
     * 
     * @type {number}
     * @memberof StockTradeHistoryModel
     */
    id?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof StockTradeHistoryModel
     */
    tradeTimeStamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof StockTradeHistoryModel
     */
    stockTickerId?: number;
    /**
     * 
     * @type {number}
     * @memberof StockTradeHistoryModel
     */
    tradeSize?: number;
    /**
     * 
     * @type {number}
     * @memberof StockTradeHistoryModel
     */
    tradeValue?: number;
    /**
     * 
     * @type {number}
     * @memberof StockTradeHistoryModel
     */
    currencySymbolId?: number;
    /**
     * 
     * @type {number}
     * @memberof StockTradeHistoryModel
     */
    userIdentityId?: number;
}

export function StockTradeHistoryModelFromJSON(json: any): StockTradeHistoryModel {
    return StockTradeHistoryModelFromJSONTyped(json, false);
}

export function StockTradeHistoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockTradeHistoryModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tradeTimeStamp': !exists(json, 'tradeTimeStamp') ? undefined : (new Date(json['tradeTimeStamp'])),
        'stockTickerId': !exists(json, 'stockTickerId') ? undefined : json['stockTickerId'],
        'tradeSize': !exists(json, 'tradeSize') ? undefined : json['tradeSize'],
        'tradeValue': !exists(json, 'tradeValue') ? undefined : json['tradeValue'],
        'currencySymbolId': !exists(json, 'currencySymbolId') ? undefined : json['currencySymbolId'],
        'userIdentityId': !exists(json, 'userIdentityId') ? undefined : json['userIdentityId'],
    };
}

export function StockTradeHistoryModelToJSON(value?: StockTradeHistoryModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tradeTimeStamp': value.tradeTimeStamp === undefined ? undefined : (value.tradeTimeStamp.toISOString()),
        'stockTickerId': value.stockTickerId,
        'tradeSize': value.tradeSize,
        'tradeValue': value.tradeValue,
        'currencySymbolId': value.currencySymbolId,
        'userIdentityId': value.userIdentityId,
    };
}
