/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class StockTickerModel
 */
export class StockTickerModel {
    /**
     * 
     * @type {number}
     * @memberof StockTickerModel
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StockTickerModel
     */
    ticker?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockTickerModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockTickerModel
     */
    metadata?: string | null;
}

export function StockTickerModelFromJSON(json: any): StockTickerModel {
    return StockTickerModelFromJSONTyped(json, false);
}

export function StockTickerModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockTickerModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ticker': !exists(json, 'ticker') ? undefined : json['ticker'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function StockTickerModelToJSON(value?: StockTickerModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ticker': value.ticker,
        'name': value.name,
        'metadata': value.metadata,
    };
}
