/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class TradeGroupedTradeTime
 */
export class TradeGroupedTradeTime {
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTradeTime
     */
    tickerId?: number;
    /**
     * 
     * @type {Date}
     * @memberof TradeGroupedTradeTime
     */
    tradeTimeStamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTradeTime
     */
    totalTradeSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTradeTime
     */
    totalTradeValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTradeTime
     */
    accumulatedTradeSize?: number;
}

export function TradeGroupedTradeTimeFromJSON(json: any): TradeGroupedTradeTime {
    return TradeGroupedTradeTimeFromJSONTyped(json, false);
}

export function TradeGroupedTradeTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeGroupedTradeTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tickerId': !exists(json, 'tickerId') ? undefined : json['tickerId'],
        'tradeTimeStamp': !exists(json, 'tradeTimeStamp') ? undefined : (new Date(json['tradeTimeStamp'])),
        'totalTradeSize': !exists(json, 'totalTradeSize') ? undefined : json['totalTradeSize'],
        'totalTradeValue': !exists(json, 'totalTradeValue') ? undefined : json['totalTradeValue'],
        'accumulatedTradeSize': !exists(json, 'accumulatedTradeSize') ? undefined : json['accumulatedTradeSize'],
    };
}

export function TradeGroupedTradeTimeToJSON(value?: TradeGroupedTradeTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tickerId': value.tickerId,
        'tradeTimeStamp': value.tradeTimeStamp === undefined ? undefined : (value.tradeTimeStamp.toISOString()),
        'totalTradeSize': value.totalTradeSize,
        'totalTradeValue': value.totalTradeValue,
        'accumulatedTradeSize': value.accumulatedTradeSize,
    };
}
