/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class TradeGroupedTicker
 */
export class TradeGroupedTicker {
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTicker
     */
    tickerId?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTicker
     */
    totalTradeSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTicker
     */
    totalTradeValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeGroupedTicker
     */
    accumulatedTradeSize?: number;
}

export function TradeGroupedTickerFromJSON(json: any): TradeGroupedTicker {
    return TradeGroupedTickerFromJSONTyped(json, false);
}

export function TradeGroupedTickerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeGroupedTicker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tickerId': !exists(json, 'tickerId') ? undefined : json['tickerId'],
        'totalTradeSize': !exists(json, 'totalTradeSize') ? undefined : json['totalTradeSize'],
        'totalTradeValue': !exists(json, 'totalTradeValue') ? undefined : json['totalTradeValue'],
        'accumulatedTradeSize': !exists(json, 'accumulatedTradeSize') ? undefined : json['accumulatedTradeSize'],
    };
}

export function TradeGroupedTickerToJSON(value?: TradeGroupedTicker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tickerId': value.tickerId,
        'totalTradeSize': value.totalTradeSize,
        'totalTradeValue': value.totalTradeValue,
        'accumulatedTradeSize': value.accumulatedTradeSize,
    };
}
