/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @class TradeHistory
 */
export class TradeHistory {
    /**
     * 
     * @type {number}
     * @memberof TradeHistory
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof TradeHistory
     */
    tradeTimeStamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof TradeHistory
     */
    cryptoTickerId?: number;
    /**
     * 
     * @type {string}
     * @memberof TradeHistory
     */
    cryptoTicker?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TradeHistory
     */
    tradeSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeHistory
     */
    tradeValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeHistory
     */
    currencySymbolId?: number;
    /**
     * 
     * @type {string}
     * @memberof TradeHistory
     */
    currencySymbol?: string | null;
}

export function TradeHistoryFromJSON(json: any): TradeHistory {
    return TradeHistoryFromJSONTyped(json, false);
}

export function TradeHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tradeTimeStamp': !exists(json, 'tradeTimeStamp') ? undefined : (new Date(json['tradeTimeStamp'])),
        'cryptoTickerId': !exists(json, 'cryptoTickerId') ? undefined : json['cryptoTickerId'],
        'cryptoTicker': !exists(json, 'cryptoTicker') ? undefined : json['cryptoTicker'],
        'tradeSize': !exists(json, 'tradeSize') ? undefined : json['tradeSize'],
        'tradeValue': !exists(json, 'tradeValue') ? undefined : json['tradeValue'],
        'currencySymbolId': !exists(json, 'currencySymbolId') ? undefined : json['currencySymbolId'],
        'currencySymbol': !exists(json, 'currencySymbol') ? undefined : json['currencySymbol'],
    };
}

export function TradeHistoryToJSON(value?: TradeHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tradeTimeStamp': value.tradeTimeStamp === undefined ? undefined : (value.tradeTimeStamp.toISOString()),
        'cryptoTickerId': value.cryptoTickerId,
        'cryptoTicker': value.cryptoTicker,
        'tradeSize': value.tradeSize,
        'tradeValue': value.tradeValue,
        'currencySymbolId': value.currencySymbolId,
        'currencySymbol': value.currencySymbol,
    };
}

