/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class TradesGroupedMonth
 */
export class TradesGroupedMonth {
    /**
     * 
     * @type {number}
     * @memberof TradesGroupedMonth
     */
    tickerId?: number;
    /**
     * 
     * @type {number}
     * @memberof TradesGroupedMonth
     */
    tradeYear?: number;
    /**
     * 
     * @type {number}
     * @memberof TradesGroupedMonth
     */
    tradeMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof TradesGroupedMonth
     */
    tradeSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TradesGroupedMonth
     */
    tradeValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TradesGroupedMonth
     */
    accumulatedTradeSize?: number;
}

export function TradesGroupedMonthFromJSON(json: any): TradesGroupedMonth {
    return TradesGroupedMonthFromJSONTyped(json, false);
}

export function TradesGroupedMonthFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradesGroupedMonth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tickerId': !exists(json, 'tickerId') ? undefined : json['tickerId'],
        'tradeYear': !exists(json, 'tradeYear') ? undefined : json['tradeYear'],
        'tradeMonth': !exists(json, 'tradeMonth') ? undefined : json['tradeMonth'],
        'tradeSize': !exists(json, 'tradeSize') ? undefined : json['tradeSize'],
        'tradeValue': !exists(json, 'tradeValue') ? undefined : json['tradeValue'],
        'accumulatedTradeSize': !exists(json, 'accumulatedTradeSize') ? undefined : json['accumulatedTradeSize'],
    };
}

export function TradesGroupedMonthToJSON(value?: TradesGroupedMonth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tickerId': value.tickerId,
        'tradeYear': value.tradeYear,
        'tradeMonth': value.tradeMonth,
        'tradeSize': value.tradeSize,
        'tradeValue': value.tradeValue,
        'accumulatedTradeSize': value.accumulatedTradeSize,
    };
}
