/* tslint:disable */
/* eslint-disable */
/**
 * ManagerWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @class BankBalanceModel
 */
export class BankBalanceModel {
    /**
     * 
     * @type {number}
     * @memberof BankBalanceModel
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof BankBalanceModel
     */
    openingBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof BankBalanceModel
     */
    balance?: number;
}

export function BankBalanceModelFromJSON(json: any): BankBalanceModel {
    return BankBalanceModelFromJSONTyped(json, false);
}

export function BankBalanceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankBalanceModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'openingBalance': !exists(json, 'openingBalance') ? undefined : json['openingBalance'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
    };
}

export function BankBalanceModelToJSON(value?: BankBalanceModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'openingBalance': value.openingBalance,
        'balance': value.balance,
    };
}


