/* tslint:disable */
/* eslint-disable */
/**
 * ManagerWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @class BudgetModel
 */
export class BudgetModel {
    /**
     * 
     * @type {number}
     * @memberof BudgetModel
     */
    id?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BudgetModel
     */
    dateFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BudgetModel
     */
    dateTo?: Date;
    /**
     * 
     * @type {number}
     * @memberof BudgetModel
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof BudgetModel
     */
    name?: string | null;
}

export function BudgetModelFromJSON(json: any): BudgetModel {
    return BudgetModelFromJSONTyped(json, false);
}

export function BudgetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'dateFrom': !exists(json, 'dateFrom') ? undefined : (new Date(json['dateFrom'])),
        'dateTo': !exists(json, 'dateTo') ? undefined : (new Date(json['dateTo'])),
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BudgetModelToJSON(value?: BudgetModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'dateFrom': value.dateFrom === undefined ? undefined : (value.dateFrom.toISOString().substr(0,10)),
        'dateTo': value.dateTo === undefined ? undefined : (value.dateTo.toISOString().substr(0,10)),
        'amount': value.amount,
        'name': value.name,
    };
}


