/* tslint:disable */
/* eslint-disable */
/**
 * ManagerWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @class PaymentCategoryModel
 */
export class PaymentCategoryModel {
    /**
     * 
     * @type {number}
     * @memberof PaymentCategoryModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCategoryModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentCategoryModel
     */
    icon?: string | null;
}

export function PaymentCategoryModelFromJSON(json: any): PaymentCategoryModel {
    return PaymentCategoryModelFromJSONTyped(json, false);
}

export function PaymentCategoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCategoryModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
    };
}

export function PaymentCategoryModelToJSON(value?: PaymentCategoryModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'icon': value.icon,
    };
}


