/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.AuthApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    TokenModel,
    TokenModelFromJSON,
    TokenModelToJSON,
    UserModel,
    UserModelFromJSON,
    UserModelToJSON,
} from '../models';

export interface AuthAuthenticatePostRequest {
    userModel?: UserModel;
}

export interface AuthTokenDataGetRequest {
    token?: string | null;
}

export interface AuthValidatePostRequest {
    tokenModel?: TokenModel;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * 
     * @param {UserModel} [userModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authAuthenticatePostRaw(requestParameters: AuthAuthenticatePostRequest): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authAuthenticatePost(requestParameters: AuthAuthenticatePostRequest): Promise<void>;

    /**
     * 
     * @param {string} [token] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authTokenDataGetRaw(requestParameters: AuthTokenDataGetRequest): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authTokenDataGet(requestParameters: AuthTokenDataGetRequest): Promise<void>;

    /**
     * 
     * @param {TokenModel} [tokenModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authValidatePostRaw(requestParameters: AuthValidatePostRequest): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authValidatePost(requestParameters: AuthValidatePostRequest): Promise<void>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     */
    async authAuthenticatePostRaw(requestParameters: AuthAuthenticatePostRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/authenticate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserModelToJSON(requestParameters.userModel),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authAuthenticatePost(requestParameters: AuthAuthenticatePostRequest): Promise<void> {
        await this.authAuthenticatePostRaw(requestParameters);
    }

    /**
     */
    async authTokenDataGetRaw(requestParameters: AuthTokenDataGetRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/tokenData`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authTokenDataGet(requestParameters: AuthTokenDataGetRequest): Promise<void> {
        await this.authTokenDataGetRaw(requestParameters);
    }

    /**
     */
    async authValidatePostRaw(requestParameters: AuthValidatePostRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenModelToJSON(requestParameters.tokenModel),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authValidatePost(requestParameters: AuthValidatePostRequest): Promise<void> {
        await this.authValidatePostRaw(requestParameters);
    }

}
