/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../runtime';
import {
    BudgetModel,
    BudgetModelFromJSON,
    BudgetModelToJSON,
} from '../models';

export interface BudgetsDeleteRequest {
    body?: number;
}

export interface BudgetsGetRequest {
    id?: number;
}

export interface BudgetsPostRequest {
    budgetModel?: BudgetModel;
}

export interface BudgetsPutRequest {
    budgetModel?: BudgetModel;
}

/**
 * BudgetApi - interface
 * 
 * @export
 * @interface BudgetApiInterface
 */
export interface BudgetApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetApiInterface
     */
    budgetsActualGetRaw(): Promise<runtime.ApiResponse<Array<BudgetModel>>>;

    /**
     */
    budgetsActualGet(): Promise<Array<BudgetModel>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetApiInterface
     */
    budgetsAllGetRaw(): Promise<runtime.ApiResponse<Array<BudgetModel>>>;

    /**
     */
    budgetsAllGet(): Promise<Array<BudgetModel>>;

    /**
     * 
     * @param {number} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetApiInterface
     */
    budgetsDeleteRaw(requestParameters: BudgetsDeleteRequest): Promise<runtime.ApiResponse<void>>;

    /**
     */
    budgetsDelete(requestParameters: BudgetsDeleteRequest): Promise<void>;

    /**
     * 
     * @param {number} [id] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetApiInterface
     */
    budgetsGetRaw(requestParameters: BudgetsGetRequest): Promise<runtime.ApiResponse<BudgetModel>>;

    /**
     */
    budgetsGet(requestParameters: BudgetsGetRequest): Promise<BudgetModel>;

    /**
     * 
     * @param {BudgetModel} [budgetModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetApiInterface
     */
    budgetsPostRaw(requestParameters: BudgetsPostRequest): Promise<runtime.ApiResponse<void>>;

    /**
     */
    budgetsPost(requestParameters: BudgetsPostRequest): Promise<void>;

    /**
     * 
     * @param {BudgetModel} [budgetModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetApiInterface
     */
    budgetsPutRaw(requestParameters: BudgetsPutRequest): Promise<runtime.ApiResponse<void>>;

    /**
     */
    budgetsPut(requestParameters: BudgetsPutRequest): Promise<void>;

}

/**
 * 
 */
export class BudgetApi extends runtime.BaseAPI implements BudgetApiInterface {

    /**
     */
    async budgetsActualGetRaw(): Promise<runtime.ApiResponse<Array<BudgetModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/budgets/actual`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetModelFromJSON));
    }

    /**
     */
    async budgetsActualGet(): Promise<Array<BudgetModel>> {
        const response = await this.budgetsActualGetRaw();
        return await response.value();
    }

    /**
     */
    async budgetsAllGetRaw(): Promise<runtime.ApiResponse<Array<BudgetModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/budgets/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetModelFromJSON));
    }

    /**
     */
    async budgetsAllGet(): Promise<Array<BudgetModel>> {
        const response = await this.budgetsAllGetRaw();
        return await response.value();
    }

    /**
     */
    async budgetsDeleteRaw(requestParameters: BudgetsDeleteRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/budgets`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async budgetsDelete(requestParameters: BudgetsDeleteRequest): Promise<void> {
        await this.budgetsDeleteRaw(requestParameters);
    }

    /**
     */
    async budgetsGetRaw(requestParameters: BudgetsGetRequest): Promise<runtime.ApiResponse<BudgetModel>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/budgets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BudgetModelFromJSON(jsonValue));
    }

    /**
     */
    async budgetsGet(requestParameters: BudgetsGetRequest): Promise<BudgetModel> {
        const response = await this.budgetsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async budgetsPostRaw(requestParameters: BudgetsPostRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/budgets`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BudgetModelToJSON(requestParameters.budgetModel),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async budgetsPost(requestParameters: BudgetsPostRequest): Promise<void> {
        await this.budgetsPostRaw(requestParameters);
    }

    /**
     */
    async budgetsPutRaw(requestParameters: BudgetsPutRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/budgets`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BudgetModelToJSON(requestParameters.budgetModel),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async budgetsPut(requestParameters: BudgetsPutRequest): Promise<void> {
        await this.budgetsPutRaw(requestParameters);
    }

}
