/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../runtime';
import {
    EnumItemModel,
    EnumItemModelFromJSON,
    EnumItemModelToJSON,
    EnumItemModelAdjusted,
    EnumItemModelAdjustedFromJSON,
    EnumItemModelAdjustedToJSON,
} from '../models';

export interface EnumItemCodeGetRequest {
    enumItemCode: string;
}

export interface TypeEnumItemTypeCodeGetRequest {
    enumItemTypeCode: string;
}

/**
 * EnumApi - interface
 * 
 * @export
 * @interface EnumApiInterface
 */
export interface EnumApiInterface {
    /**
     * 
     * @param {string} enumItemCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnumApiInterface
     */
    enumItemCodeGetRaw(requestParameters: EnumItemCodeGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<EnumItemModelAdjusted>>;

    /**
     */
    enumItemCodeGet(requestParameters: EnumItemCodeGetRequest, initOverrides?: RequestInit): Promise<EnumItemModelAdjusted>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnumApiInterface
     */
    enumItemGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<EnumItemModel>>>;

    /**
     */
    enumItemGet(initOverrides?: RequestInit): Promise<Array<EnumItemModel>>;

    /**
     * 
     * @param {string} enumItemTypeCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnumApiInterface
     */
    typeEnumItemTypeCodeGetRaw(requestParameters: TypeEnumItemTypeCodeGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<EnumItemModelAdjusted>>>;

    /**
     */
    typeEnumItemTypeCodeGet(requestParameters: TypeEnumItemTypeCodeGetRequest, initOverrides?: RequestInit): Promise<Array<EnumItemModelAdjusted>>;

}

/**
 * 
 */
export class EnumApi extends runtime.BaseAPI implements EnumApiInterface {
    processPathParam(param: any): string {
        if (param instanceof Date)
            return encodeURIComponent(String(param.toISOString()));

        return encodeURIComponent(String(param));
    }

    /**
     */
    async enumItemCodeGetRaw(requestParameters: EnumItemCodeGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<EnumItemModelAdjusted>> {
        if (requestParameters.enumItemCode === null || requestParameters.enumItemCode === undefined) {
            throw new runtime.RequiredError('enumItemCode','Required parameter requestParameters.enumItemCode was null or undefined when calling enumItemCodeGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/{enumItemCode}`.replace(`{${"enumItemCode"}}`, this.processPathParam(requestParameters.enumItemCode)),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnumItemModelAdjustedFromJSON(jsonValue));
    }

    /**
     */
    async enumItemCodeGet(requestParameters: EnumItemCodeGetRequest, initOverrides?: RequestInit): Promise<EnumItemModelAdjusted> {
        const response = await this.enumItemCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async enumItemGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<EnumItemModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/enumItem`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnumItemModelFromJSON));
    }

    /**
     */
    async enumItemGet(initOverrides?: RequestInit): Promise<Array<EnumItemModel>> {
        const response = await this.enumItemGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async typeEnumItemTypeCodeGetRaw(requestParameters: TypeEnumItemTypeCodeGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<EnumItemModelAdjusted>>> {
        if (requestParameters.enumItemTypeCode === null || requestParameters.enumItemTypeCode === undefined) {
            throw new runtime.RequiredError('enumItemTypeCode','Required parameter requestParameters.enumItemTypeCode was null or undefined when calling typeEnumItemTypeCodeGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/type/{enumItemTypeCode}`.replace(`{${"enumItemTypeCode"}}`, this.processPathParam(requestParameters.enumItemTypeCode)),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnumItemModelAdjustedFromJSON));
    }

    /**
     */
    async typeEnumItemTypeCodeGet(requestParameters: TypeEnumItemTypeCodeGetRequest, initOverrides?: RequestInit): Promise<Array<EnumItemModelAdjusted>> {
        const response = await this.typeEnumItemTypeCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
