/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class AddTagModel
 */
export class AddTagModel {
    /**
     * 
     * @type {string}
     * @memberof AddTagModel
     */
    code?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddTagModel
     */
    paymentId?: number;
}

export function AddTagModelFromJSON(json: any): AddTagModel {
    return AddTagModelFromJSONTyped(json, false);
}

export function AddTagModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTagModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'paymentId': !exists(json, 'paymentId') ? undefined : json['paymentId'],
    };
}

export function AddTagModelToJSON(value?: AddTagModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'paymentId': value.paymentId,
    };
}

