/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    OtherInvestmentBalaceHistoryModel,
    OtherInvestmentBalaceHistoryModelFromJSON,
    OtherInvestmentBalaceHistoryModelFromJSONTyped,
    OtherInvestmentBalaceHistoryModelToJSON,
} from './OtherInvestmentBalaceHistoryModel';

/**
 * 
 * @export
 * @class OtherInvestmentBalanceSummaryModel
 */
export class OtherInvestmentBalanceSummaryModel {
    /**
     * 
     * @type {Array<OtherInvestmentBalaceHistoryModel>}
     * @memberof OtherInvestmentBalanceSummaryModel
     */
    actualBalanceData?: Array<OtherInvestmentBalaceHistoryModel> | null;
    /**
     * 
     * @type {Array<OtherInvestmentBalaceHistoryModel>}
     * @memberof OtherInvestmentBalanceSummaryModel
     */
    oneYearEarlierBalanceData?: Array<OtherInvestmentBalaceHistoryModel> | null;
}

export function OtherInvestmentBalanceSummaryModelFromJSON(json: any): OtherInvestmentBalanceSummaryModel {
    return OtherInvestmentBalanceSummaryModelFromJSONTyped(json, false);
}

export function OtherInvestmentBalanceSummaryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtherInvestmentBalanceSummaryModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actualBalanceData': !exists(json, 'actualBalanceData') ? undefined : (json['actualBalanceData'] === null ? null : (json['actualBalanceData'] as Array<any>).map(OtherInvestmentBalaceHistoryModelFromJSON)),
        'oneYearEarlierBalanceData': !exists(json, 'oneYearEarlierBalanceData') ? undefined : (json['oneYearEarlierBalanceData'] === null ? null : (json['oneYearEarlierBalanceData'] as Array<any>).map(OtherInvestmentBalaceHistoryModelFromJSON)),
    };
}

export function OtherInvestmentBalanceSummaryModelToJSON(value?: OtherInvestmentBalanceSummaryModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actualBalanceData': value.actualBalanceData === undefined ? undefined : (value.actualBalanceData === null ? null : (value.actualBalanceData as Array<any>).map(OtherInvestmentBalaceHistoryModelToJSON)),
        'oneYearEarlierBalanceData': value.oneYearEarlierBalanceData === undefined ? undefined : (value.oneYearEarlierBalanceData === null ? null : (value.oneYearEarlierBalanceData as Array<any>).map(OtherInvestmentBalaceHistoryModelToJSON)),
    };
}
