/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class PaymentModel
 */
export class PaymentModel {
    /**
     * 
     * @type {number}
     * @memberof PaymentModel
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentModel
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentModel
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PaymentModel
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof PaymentModel
     */
    bankAccountId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentModel
     */
    paymentTypeId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentModel
     */
    paymentCategoryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentModel
     */
    paymentTypeCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentModel
     */
    paymentCategoryIcon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentModel
     */
    paymentCategoryCode?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentModel
     */
    tags?: Array<string> | null;
}

export function PaymentModelFromJSON(json: any): PaymentModel {
    return PaymentModelFromJSONTyped(json, false);
}

export function PaymentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'bankAccountId': !exists(json, 'bankAccountId') ? undefined : json['bankAccountId'],
        'paymentTypeId': !exists(json, 'paymentTypeId') ? undefined : json['paymentTypeId'],
        'paymentCategoryId': !exists(json, 'paymentCategoryId') ? undefined : json['paymentCategoryId'],
        'paymentTypeCode': !exists(json, 'paymentTypeCode') ? undefined : json['paymentTypeCode'],
        'paymentCategoryIcon': !exists(json, 'paymentCategoryIcon') ? undefined : json['paymentCategoryIcon'],
        'paymentCategoryCode': !exists(json, 'paymentCategoryCode') ? undefined : json['paymentCategoryCode'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function PaymentModelToJSON(value?: PaymentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'amount': value.amount,
        'name': value.name,
        'description': value.description,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'bankAccountId': value.bankAccountId,
        'paymentTypeId': value.paymentTypeId,
        'paymentCategoryId': value.paymentCategoryId,
        'paymentTypeCode': value.paymentTypeCode,
        'paymentCategoryIcon': value.paymentCategoryIcon,
        'paymentCategoryCode': value.paymentCategoryCode,
        'tags': value.tags,
    };
}
