/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @class TickerRequest
 */
export class TickerRequest {
    /**
     * 
     * @type {string}
     * @memberof TickerRequest
     */
    ticker?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TickerRequest
     */
    userId?: number;
}

export function TickerRequestFromJSON(json: any): TickerRequest {
    return TickerRequestFromJSONTyped(json, false);
}

export function TickerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TickerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ticker': !exists(json, 'ticker') ? undefined : json['ticker'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function TickerRequestToJSON(value?: TickerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ticker': value.ticker,
        'userId': value.userId,
    };
}
