/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    BankAccount,
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
    CryptoTradeHistory,
    CryptoTradeHistoryFromJSON,
    CryptoTradeHistoryFromJSONTyped,
    CryptoTradeHistoryToJSON,
    UserData,
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './';

/**
 * 
 * @export
 * @class UserIdentity
 */
export class UserIdentity {
    /**
     * 
     * @type {number}
     * @memberof UserIdentity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserIdentity
     */
    login?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserIdentity
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {UserData}
     * @memberof UserIdentity
     */
    userData?: UserData;
    /**
     * 
     * @type {Array<BankAccount>}
     * @memberof UserIdentity
     */
    bankAccounts?: Array<BankAccount> | null;
    /**
     * 
     * @type {Array<CryptoTradeHistory>}
     * @memberof UserIdentity
     */
    cryptoTradesHistory?: Array<CryptoTradeHistory> | null;
}

export function UserIdentityFromJSON(json: any): UserIdentity {
    return UserIdentityFromJSONTyped(json, false);
}

export function UserIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdentity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'login': !exists(json, 'login') ? undefined : json['login'],
        'passwordHash': !exists(json, 'passwordHash') ? undefined : json['passwordHash'],
        'userData': !exists(json, 'userData') ? undefined : UserDataFromJSON(json['userData']),
        'bankAccounts': !exists(json, 'bankAccounts') ? undefined : (json['bankAccounts'] === null ? null : (json['bankAccounts'] as Array<any>).map(BankAccountFromJSON)),
        'cryptoTradesHistory': !exists(json, 'cryptoTradesHistory') ? undefined : (json['cryptoTradesHistory'] === null ? null : (json['cryptoTradesHistory'] as Array<any>).map(CryptoTradeHistoryFromJSON)),
    };
}

export function UserIdentityToJSON(value?: UserIdentity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'login': value.login,
        'passwordHash': value.passwordHash,
        'userData': UserDataToJSON(value.userData),
        'bankAccounts': value.bankAccounts === undefined ? undefined : (value.bankAccounts === null ? null : (value.bankAccounts as Array<any>).map(BankAccountToJSON)),
        'cryptoTradesHistory': value.cryptoTradesHistory === undefined ? undefined : (value.cryptoTradesHistory === null ? null : (value.cryptoTradesHistory as Array<any>).map(CryptoTradeHistoryToJSON)),
    };
}


