/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    UserIdentity,
    UserIdentityFromJSON,
    UserIdentityFromJSONTyped,
    UserIdentityToJSON,
} from './UserIdentity';

/**
 * 
 * @export
 * @class UserData
 */
export class UserData {
    /**
     * 
     * @type {number}
     * @memberof UserData
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof UserData
     */
    userIdentityId?: number;
    /**
     * 
     * @type {UserIdentity}
     * @memberof UserData
     */
    userIdentity?: UserIdentity;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    lastName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserData
     */
    isLocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    email?: string | null;
}

export function UserDataFromJSON(json: any): UserData {
    return UserDataFromJSONTyped(json, false);
}

export function UserDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userIdentityId': !exists(json, 'userIdentityId') ? undefined : json['userIdentityId'],
        'userIdentity': !exists(json, 'userIdentity') ? undefined : UserIdentityFromJSON(json['userIdentity']),
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'isLocked': !exists(json, 'isLocked') ? undefined : json['isLocked'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserDataToJSON(value?: UserData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userIdentityId': value.userIdentityId,
        'userIdentity': UserIdentityToJSON(value.userIdentity),
        'firstName': value.firstName,
        'lastName': value.lastName,
        'isLocked': value.isLocked,
        'phone': value.phone,
        'email': value.email,
    };
}
