/* tslint:disable */
/* eslint-disable */
/**
 * API Title
 * API Description. This API version has been deprecated.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../runtime';
import {
    ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    UserCreateModel,
    UserCreateModelFromJSON,
    UserCreateModelToJSON,
} from '../models';

export interface UserV1RegisterPostRequest {
    userCreateModel?: UserCreateModel;
}

/**
 * UserApi - interface
 * 
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
    /**
     * 
     * @param {UserCreateModel} [userCreateModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    userV1RegisterPostRaw(requestParameters: UserV1RegisterPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    userV1RegisterPost(requestParameters: UserV1RegisterPostRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI implements UserApiInterface {
    processPathParam(param: any): string {
        if (param instanceof Date)
            return encodeURIComponent(String(param.toISOString()));

        return encodeURIComponent(String(param));
    }

    /**
     */
    async userV1RegisterPostRaw(requestParameters: UserV1RegisterPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json; ver=1.0';

        const response = await this.request({
            path: `/user/v1/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateModelToJSON(requestParameters.userCreateModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userV1RegisterPost(requestParameters: UserV1RegisterPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.userV1RegisterPostRaw(requestParameters, initOverrides);
    }

}
