FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app

ENV ASPNETCORE_URLS="https://+;http://+" 
ENV ASPNETCORE_HTTPS_PORT=6011
ENV ASPNETCORE_ENVIRONMENT="Development"
# ENV ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
# ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

EXPOSE 80 
EXPOSE 443

# ENV ASPNETCORE_URLS=https://+:443;http://+:80

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["BudgetManager.AuthApi/BudgetManager.AuthApi.csproj", "BudgetManager.AuthApi/"]
RUN dotnet restore "BudgetManager.AuthApi/BudgetManager.AuthApi.csproj"
COPY . .
WORKDIR "/src/BudgetManager.AuthApi"
RUN dotnet build "BudgetManager.AuthApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BudgetManager.AuthApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BudgetManager.AuthApi.dll"]
