/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.FinancialApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../runtime';

export interface GetStockPriceDataRequest {
    ticker?: string;
}

export interface GetStockPriceDataAtDateRequest {
    date: Date;
    ticker?: string;
}

export interface GetStockPriceDataFromDateRequest {
    from: Date;
    ticker?: string;
}

/**
 * StockEndpointsApi - interface
 * 
 * @export
 * @interface StockEndpointsApiInterface
 */
export interface StockEndpointsApiInterface {
    /**
     * 
     * @param {string} [ticker] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StockEndpointsApiInterface
     */
    getStockPriceDataRaw(requestParameters: GetStockPriceDataRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    getStockPriceData(requestParameters: GetStockPriceDataRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @param {Date} date 
     * @param {string} [ticker] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StockEndpointsApiInterface
     */
    getStockPriceDataAtDateRaw(requestParameters: GetStockPriceDataAtDateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    getStockPriceDataAtDate(requestParameters: GetStockPriceDataAtDateRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @param {Date} from 
     * @param {string} [ticker] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StockEndpointsApiInterface
     */
    getStockPriceDataFromDateRaw(requestParameters: GetStockPriceDataFromDateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    getStockPriceDataFromDate(requestParameters: GetStockPriceDataFromDateRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class StockEndpointsApi extends runtime.BaseAPI implements StockEndpointsApiInterface {
    processPathParam(param: any): string {
        if (param instanceof Date)
            return encodeURIComponent(String(param.toISOString()));

        return encodeURIComponent(String(param));
    }

    /**
     */
    async getStockPriceDataRaw(requestParameters: GetStockPriceDataRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/stock/{ticker}/price/all`.replace(`{${"ticker"}}`, this.processPathParam(requestParameters.ticker)),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getStockPriceData(requestParameters: GetStockPriceDataRequest, initOverrides?: RequestInit): Promise<void> {
        await this.getStockPriceDataRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getStockPriceDataAtDateRaw(requestParameters: GetStockPriceDataAtDateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.date === null || requestParameters.date === undefined) {
            throw new runtime.RequiredError('date','Required parameter requestParameters.date was null or undefined when calling getStockPriceDataAtDate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/stock/{ticker}/price/{date}`.replace(`{${"ticker"}}`, this.processPathParam(requestParameters.ticker)).replace(`{${"date"}}`, this.processPathParam(requestParameters.date)),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getStockPriceDataAtDate(requestParameters: GetStockPriceDataAtDateRequest, initOverrides?: RequestInit): Promise<void> {
        await this.getStockPriceDataAtDateRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getStockPriceDataFromDateRaw(requestParameters: GetStockPriceDataFromDateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.from === null || requestParameters.from === undefined) {
            throw new runtime.RequiredError('from','Required parameter requestParameters.from was null or undefined when calling getStockPriceDataFromDate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/stock/{ticker}/priceFrom/{from}`.replace(`{${"ticker"}}`, this.processPathParam(requestParameters.ticker)).replace(`{${"from"}}`, this.processPathParam(requestParameters.from)),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getStockPriceDataFromDate(requestParameters: GetStockPriceDataFromDateRequest, initOverrides?: RequestInit): Promise<void> {
        await this.getStockPriceDataFromDateRaw(requestParameters, initOverrides);
    }

}
