/* tslint:disable */
/* eslint-disable */
/**
 * BudgetManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../runtime';
import {
    ComodityTradeHistoryModel,
    ComodityTradeHistoryModelFromJSON,
    ComodityTradeHistoryModelToJSON,
    ComodityTypeModel,
    ComodityTypeModelFromJSON,
    ComodityTypeModelToJSON,
    ComodityUnitModel,
    ComodityUnitModelFromJSON,
    ComodityUnitModelToJSON,
} from '../models';

export interface ComoditiesDeleteRequest {
    body?: number;
}

export interface ComoditiesGoldActualPriceCurrencyCodeGetRequest {
    currencyCode: string | null;
}

export interface ComoditiesPostRequest {
    comodityTradeHistoryModel?: ComodityTradeHistoryModel;
}

export interface ComoditiesPutRequest {
    comodityTradeHistoryModel?: ComodityTradeHistoryModel;
}

/**
 * ComodityApi - interface
 * 
 * @export
 * @interface ComodityApiInterface
 */
export interface ComodityApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesAllGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ComodityTradeHistoryModel>>>;

    /**
     */
    comoditiesAllGet(initOverrides?: RequestInit): Promise<Array<ComodityTradeHistoryModel>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesComodityTypeAllGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ComodityTypeModel>>>;

    /**
     */
    comoditiesComodityTypeAllGet(initOverrides?: RequestInit): Promise<Array<ComodityTypeModel>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesComodityUnitAllGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ComodityUnitModel>>>;

    /**
     */
    comoditiesComodityUnitAllGet(initOverrides?: RequestInit): Promise<Array<ComodityUnitModel>>;

    /**
     * 
     * @param {number} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesDeleteRaw(requestParameters: ComoditiesDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    comoditiesDelete(requestParameters: ComoditiesDeleteRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @param {string} currencyCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesGoldActualPriceCurrencyCodeGetRaw(requestParameters: ComoditiesGoldActualPriceCurrencyCodeGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>>;

    /**
     */
    comoditiesGoldActualPriceCurrencyCodeGet(requestParameters: ComoditiesGoldActualPriceCurrencyCodeGetRequest, initOverrides?: RequestInit): Promise<number>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesGoldActualPriceGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>>;

    /**
     */
    comoditiesGoldActualPriceGet(initOverrides?: RequestInit): Promise<number>;

    /**
     * 
     * @param {ComodityTradeHistoryModel} [comodityTradeHistoryModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesPostRaw(requestParameters: ComoditiesPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    comoditiesPost(requestParameters: ComoditiesPostRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @param {ComodityTradeHistoryModel} [comodityTradeHistoryModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ComodityApiInterface
     */
    comoditiesPutRaw(requestParameters: ComoditiesPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    comoditiesPut(requestParameters: ComoditiesPutRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class ComodityApi extends runtime.BaseAPI implements ComodityApiInterface {
    processPathParam(param: any): string {
        if (param instanceof Date)
            return encodeURIComponent(String(param.toISOString()));

        return encodeURIComponent(String(param));
    }

    /**
     */
    async comoditiesAllGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ComodityTradeHistoryModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ComodityTradeHistoryModelFromJSON));
    }

    /**
     */
    async comoditiesAllGet(initOverrides?: RequestInit): Promise<Array<ComodityTradeHistoryModel>> {
        const response = await this.comoditiesAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async comoditiesComodityTypeAllGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ComodityTypeModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities/comodityType/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ComodityTypeModelFromJSON));
    }

    /**
     */
    async comoditiesComodityTypeAllGet(initOverrides?: RequestInit): Promise<Array<ComodityTypeModel>> {
        const response = await this.comoditiesComodityTypeAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async comoditiesComodityUnitAllGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ComodityUnitModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities/comodityUnit/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ComodityUnitModelFromJSON));
    }

    /**
     */
    async comoditiesComodityUnitAllGet(initOverrides?: RequestInit): Promise<Array<ComodityUnitModel>> {
        const response = await this.comoditiesComodityUnitAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async comoditiesDeleteRaw(requestParameters: ComoditiesDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async comoditiesDelete(requestParameters: ComoditiesDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.comoditiesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async comoditiesGoldActualPriceCurrencyCodeGetRaw(requestParameters: ComoditiesGoldActualPriceCurrencyCodeGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        if (requestParameters.currencyCode === null || requestParameters.currencyCode === undefined) {
            throw new runtime.RequiredError('currencyCode','Required parameter requestParameters.currencyCode was null or undefined when calling comoditiesGoldActualPriceCurrencyCodeGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities/gold/actualPrice/{currencyCode}`.replace(`{${"currencyCode"}}`, this.processPathParam(requestParameters.currencyCode)),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async comoditiesGoldActualPriceCurrencyCodeGet(requestParameters: ComoditiesGoldActualPriceCurrencyCodeGetRequest, initOverrides?: RequestInit): Promise<number> {
        const response = await this.comoditiesGoldActualPriceCurrencyCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async comoditiesGoldActualPriceGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities/gold/actualPrice`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async comoditiesGoldActualPriceGet(initOverrides?: RequestInit): Promise<number> {
        const response = await this.comoditiesGoldActualPriceGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async comoditiesPostRaw(requestParameters: ComoditiesPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ComodityTradeHistoryModelToJSON(requestParameters.comodityTradeHistoryModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async comoditiesPost(requestParameters: ComoditiesPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.comoditiesPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async comoditiesPutRaw(requestParameters: ComoditiesPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/comodities`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ComodityTradeHistoryModelToJSON(requestParameters.comodityTradeHistoryModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async comoditiesPut(requestParameters: ComoditiesPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.comoditiesPutRaw(requestParameters, initOverrides);
    }

}
